import type { AIPayload } from '../types';

const DELAY_MS = 1800;

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

const COVER_LETTER = (contexts: AIPayload['contexts'], model: string): string => {
  const resume = contexts.find((c) => c.title.toLowerCase().includes('resume'));
  const job = contexts.find(
    (c) => c.title.toLowerCase().includes('job') || c.title.toLowerCase().includes('description')
  );
  const notes = contexts.find(
    (c) => c.title.toLowerCase().includes('note') || c.title.toLowerCase().includes('personal')
  );

  const company = job ? 'TechCorp' : 'the company';
  const role = job ? 'Senior Frontend Engineer' : 'the role';
  const years = resume ? '5' : 'several';

  return `Dear Hiring Manager,

I am writing to express my enthusiastic interest in the ${role} position at ${company}. With over ${years} years of experience architecting scalable web applications using React and Node.js, I am confident that my background aligns strongly with your requirements.

${job ? `My experience at PreviousCo aligns perfectly with your requirement for high-performance UI optimization. I successfully reduced load times by 40%, improved Core Web Vitals scores by 35%, and led a team of 6 engineers through a complete design system overhaul.` : `I have spent the past several years building and scaling frontend systems that serve millions of users.`}

${resume ? `Throughout my career, I've championed TypeScript adoption, implemented micro-frontend architectures, and built component libraries used across multiple product lines.` : ''}

${notes ? `I'd also love to share my recent side project — an AI-powered data visualization tool that has gained significant traction in the developer community.` : ''}

I would love the opportunity to discuss how my experience can contribute to ${company}'s goals.

Thank you for your time and consideration.

Warm regards,
Alex Chen

---
*Generated by Context Stacker using ${model} • ${contexts.length} context block${contexts.length !== 1 ? 's' : ''} used*`;
};

const GENERIC_OUTPUT = (payload: AIPayload): string => {
  const summary = payload.contexts
    .map((c) => `• @${c.title}: ${c.content.slice(0, 80)}...`)
    .join('\n');

  return `Based on your context blocks:\n\n${summary || '(no contexts connected)'}\n\n${payload.instructions}\n\n---\n*Generated by Context Stacker using ${payload.model}*`;
};

export async function generateOutput(payload: AIPayload): Promise<string> {
  await sleep(DELAY_MS);

  const isCoverLetter =
    payload.instructions.toLowerCase().includes('cover letter') ||
    payload.instructions.toLowerCase().includes('hiring');

  if (isCoverLetter && payload.contexts.length > 0) {
    return COVER_LETTER(payload.contexts, payload.model);
  }

  return GENERIC_OUTPUT(payload);
}
